[phases.setup]
nixPkgs = ["python311Full", "python311Packages.pip", "nodejs-18_x"]

[phases.install]
cmds = [
  "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python3 get-pip.py",
  "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python3 -m src.main"