[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv", "nodejs-18_x"]

[phases.install]
cmds = [
  "python3 -m venv .venv",
  "source .venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "source .venv/bin/activate && python -m src.main"