[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs-18_x"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python3 -m src.main"