[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python3 -m src.main"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[deploy.environmentVariables]]
name = "PORT"
value = "8080"

[[deploy.environmentVariables]]
name = "PYTHONUNBUFFERED"
value = "1"
