[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python enhanced_main_v2.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[deploy.environmentVariables]]
name = "PORT"
value = "8080"

[[deploy.environmentVariables]]
name = "PYTHONUNBUFFERED"
value = "1"
